version: '3'
services:
  node-app:
    container_name: version-one-mobser-container
    image: hazemhamdy/mobser-be
    build: 
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./config.env
    depends_on:
      - redis
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
  redis:
    image: redis